# Generated by Django 4.2.9 on 2024-01-10 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_type', models.CharField(choices=[('RECTANGLE', 'RECTANGLE'), ('LINE', 'LINE'), ('CIRCLE', 'CIRCLE'), ('SQUARE', 'SQUARE'), ('TRIANGLE', 'TRIANGLE'), ('OVAL', 'OVAL'), ('ARROW', 'ARROW'), ('HEXAGON', 'HEXAGON'), ('PENTAGON', 'PENTAGON'), ('STAR', 'STAR')], max_length=50)),
                ('coordinates', models.TextField()),
                ('dimensions', models.TextField(blank=True, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drawing')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('position', models.TextField()),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shape')),
            ],
        ),
    ]
