# Generated by Django 4.2.9 on 2024-01-10 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='shape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shape'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shape',
            name='drawing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.drawing'),
        ),
    ]
